### ISSUE TITLE
Not live reloading

### ISSUE THREAD

**Issue by cesarferreira** [jhabdas/react-native-webpack-starter-kit#12]
Hey, first of all, awesome work! Thanks for sharing it with the world.

What I'm doing:
after installing the dependencies...

1. Open the `.xcodeproj`
2. Run `npm start`
3. Run the app on the emulator
4. Enable live reloading
5. Changes to the code are not reflected, I need to `cmd+r` to see them

Am I missing something?

**Comment by jhabdas** [comment]
Looking at [Facebook's Live Reload doc](https://facebook.github.io/react-native/docs/debugging.html#live-reload) it looks like the reload feature works when "changes are made to the JavaScript", which I presume means either the `index.ios.js` or `index.android.js` files are saved while the React Packager is running.

The way the Webpack Dev Server works is the two `index` files are generated as opposed to modified and saved, which may be what's preventing the React Packager from signaling a live reload. Rather than fighting to get it to work consider instead looking at [Hot Module Replacement technique](https://github.com/mjohnston/react-native-webpack-server#hot-module-replacement) being pursued and maintained with the RNWS dependency this kit leverages to generate the `index` files.
