### ISSUE TITLE
[fatal][tid:main] Unable to execute JS call: __fbBatchedBridge is undefined

### ISSUE THREAD

**Issue by E-P1983** [jhabdas/react-native-webpack-starter-kit#134]
Whenever I try to create a offline bundle with the directions given I get the error:

[fatal][tid:main] Unable to execute JS call: __fbBatchedBridge is undefined

I tried different solutions using https://github.com/facebook/react-native/issues/5770 but currently I'm stuck. 

I don't know if this is related to the starter kit or not, so any tips/hints/pointers to rule out the starter kit and the way it packages would be helpful.

**Comment by jhabdas** [comment]
@E-P1983 Thanks for the report and sorry for your troubles. I was able to replicate with kit version `v2.29.0` and also tried a few of the suggestions in the linked open issue, including:

- Hacking the `react-native.xcode.sh` bash script
- Setting the Scheme to _Release_ mode

Unfortunately, I was not able to get past the error and can't afford much time right now to address it. Because this kit was developed before RN had as much tooling baked into the core the plates shifting underneath have caused similar types of issues in the past.

Until this is fixed my suggestion would be to use the `react-native-cli` to `init` a new project and see if you can reproduce the issue. That'll help identify if it's a kit issue or RN. I'll keep this issue open until we can learn more. Thanks for your help.

**Comment by egauci** [comment]
Here's what finally worked for me.

I saw a suggestion to reinstall watchman. I had installed that with brew, so I did "brew reinstall watchman"

When that completed, I restarted the computer.

After that, things worked!

I don't know if that will fix it for everyone, but its worth a shot.

**Comment by jhabdas** [comment]
Thanks for the update, @egauci. Glad you got it working! There's no doubt this will come in handy for someone. :) Cheers
