### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [jhabdas/react-native-webpack-starter-kit#157]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by jhabdas** [comment]
Hell yeah it would!

**Comment by jhabdas** [comment]
Sub pull at your leisure

**Comment by amilajack** [comment]
Sorry that I didn't follow up on this! I'll PR now.

**Comment by jhabdas** [comment]
No sweat @amilajack. I'm sure if you do someone will find value. Though deprecated, this project still sees ~4K visitors / mo.

**Comment by amilajack** [comment]
Why was this deprecated? 😢

**Comment by jhabdas** [comment]
I main reason I deprecated it because I couldn't get RN versions after the current version in the manifest working properly. Be happy to bring it back to life if we can get it working with `0.35`. I'll give it a show with your PR tomorrow :)

https://github.com/jhabdas/react-native-webpack-starter-kit/pull/158
