### ISSUE TITLE
Missing dependency err after fresh clone

### ISSUE THREAD

**Issue by MrChristofferson** [jhabdas/react-native-webpack-starter-kit#56]
Shows up for both ios and android js files:

<img width="488" alt="screen shot 2016-02-27 at 5 23 05 pm" src="https://cloud.githubusercontent.com/assets/12105346/13376338/f978ec60-dd76-11e5-8427-88a403019d34.png">

**Comment by jhabdas** [comment]
Take a peek later. As the README states linting rules are intended to be
sane, which Airbnb is not. What happens when you clone fresh and install?
You didn't provide much context otherwise to help.
On Sat, Feb 27, 2016 at 6:25 PM Chris Vandenberg <notifications@github.com>
wrote:

> Shows up for both ios and android js files:
>
> [image: screen shot 2016-02-27 at 5 23 05 pm]
> <https://cloud.githubusercontent.com/assets/12105346/13376338/f978ec60-dd76-11e5-8427-88a403019d34.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhabdas/react-native-webpack-starter-kit/issues/56>.
>
-- 
Josh Habdas
tel: +1 (630) 290-3542
web: http://habd.as
