### ISSUE TITLE
Readme file claims incorrectly that standard react-native init causes problems.

### ISSUE THREAD

**Issue by obromios** [jhabdas/react-native-webpack-starter-kit#85]
Your README file claims that:

> Unlike the app currently generated by react-native init this app removes the UIViewControllerBasedStatusBarAppearance key to prevent the app from logging an error in Xcode and leading to an App Store rejection.

I raised that as an [issue](https://github.com/facebook/react-native/issues/6892#event-621477181) on the react-native site, but the issue was closed as it was deemed that the above statement in your README was incorrect.  Can  you please either correct the README file, or reopen the  [issue](https://github.com/facebook/react-native/issues/6892#event-621477181).

**Comment by jhabdas** [comment]
I'm not able to reopen the RN issue, but I certainly commented on it and tagged @ide as that issue cost me several shameful hours of debugging after an unexpected app store rejection. The bugger of it all was that everything else was correct and Apple provided no specific information as to what was causing the rejection. What finally tipped me off was that I could find no other problems; the related error I was only able to see in Xcode console upon running a build, but it did not otherwise seem to affect the app. If Xcode console errors no longer occur when left default it may not be an issue with the App Store approval any longer. I for one, would never want to find out again.

**Comment by jhabdas** [comment]
If Xcode no longer throws an error with the status bar appearance setting for iOS we should be safe to remove the customization made to this kit. Thanks for coordinating @oboramios.
